name: delivery
description: 'A new Flutter project. Created by Slidy'
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dio: ^5.0.0
  mobx: ^2.4.0
  flutter_mobx: ^2.2.0
  flutter_modular: ^6.3.4
  carousel_slider: ^5.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^2.4.0
  build_runner: ^2.4.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  file: ^7.0.0
