name: delivery
description: 'A new Flutter project. Created by Slidy'
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  flutter_modular: ^3.4.1+1
  carousel_slider: ^4.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  mobx_codegen: ^2.0.3
  build_runner: ^2.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
